### ISSUE TITLE
UI: Vehicle List

### ISSUE THREAD

**Issue by felixrieseberg** [felixrieseberg/OxideFleet#38]
As a user I want to be able to easily open an Active Vehicle list view that is positioned next to, or overlaid on top of, the map view so that I can quickly scan the list of active vehicles.

Each active vehicle should be in the list.
The list should be ordered alphabetically by vehicle name.
The list should display the vehicle name, VIN, driver name and current driver score.
Clicking on the vehicle name should navigate to the vehicle summary view.
Clicking on the driver name should navigate to the driver summary view.

**Comment by felixrieseberg** [comment]
Comp:

![desktop_layout_active_driver_summary](https://cloud.githubusercontent.com/assets/1426799/7476096/4ab46350-f300-11e4-85d8-48ab77dc7478.jpeg)

**Comment by sedouard** [comment]
Isn't whats displayed on the left https://github.com/felixrieseberg/OxideFleet/issues/40 ?

**Comment by felixrieseberg** [comment]
Correct.

**Comment by felixrieseberg** [comment]
Nah, I want two issues - one for the top thing, one for the bottom (detail view). I want my gratification!

**Comment by sedouard** [comment]
wait - is that a mockup or... is that actually implemented?

**Comment by felixrieseberg** [comment]
That's just a mockup, so we still have to build it 😄

**Comment by sedouard** [comment]
:laughing: I was like 'why don't you just commit the damn thing!'. got it
