### ISSUE TITLE
Get rid of LS Adapter for Nitrogen Messaging

### ISSUE THREAD

**Issue by sedouard** [felixrieseberg/OxideFleet#57]
As @felixrieseberg mentioned, we should refactor nitrogen to work on messaging from the vehicle model instead of having it sit in auxiliary code which doesn't really fit well.

This will also make things simpler by just having 1 adapter for the rest api, instead of maintaining 2, one for local storage and the other for the rest api.

**Comment by felixrieseberg** [comment]
Awaiting @timfpark for comment.

**Comment by felixrieseberg** [comment]
I'm actually quite happy with the current implementation - given that devices will now come from Nitrogen, we can keep it around.
