### ISSUE TITLE
Mobile: Sidebar

### ISSUE THREAD

**Issue by felixrieseberg** [felixrieseberg/OxideFleet#6]
The sidebar on the dashboard can currently not be moved or disabled, resulting in a somewhat horrible mobile user experience. A swap-in/out solution should help.

**Comment by deadlyfingers** [comment]
This might be worth a look: http://stackoverflow.com/questions/19041801/bootstrap-3-0-sliding-menu-from-left

**Comment by felixrieseberg** [comment]
I also made a somewhat simple implementation in Oxide that you could just copy (https://github.com/nitrogenjs/oxide/blob/master/app/views/application.js). I simply used jQuery to animate the width of the panel and the margin of the main content div.
