### ISSUE TITLE
API Changes Required to Implement Scenarios

### ISSUE THREAD

**Issue by felixrieseberg** [felixrieseberg/OxideFleet#66]
This is a collection of changes required to satisfy the scenarios. We need endpoints for the following:

* [x] Currently active trip on a vehicle
* [x] Driver Score

**Comment by sedouard** [comment]
the driver [spec](https://github.com/felixrieseberg/OxideFleet/blob/master/specs/rest-api.md#get-driversid---returns-a-driver-with-specified-id) shows `driver_score` is already there

**Comment by felixrieseberg** [comment]
Thanks, I just didn't find it. So we only display it if the car is currently active, I guess. What's the intended flow?

Vehicle (is active) -> Get Latest Trip -> Get Driver -> Get Score?

**Comment by sedouard** [comment]
that's how i'm doing it in the test right now. right now theres a relationship between trips and drivers. but vehicle and driver. so when you show a driver score you should be aware that it's not really for the vehicle, but for the driver. which today is the same thing (and maybe for demo purpose, will always be)

**Comment by sedouard** [comment]
Anything else needed here felix? Can I we close this out? I believe currently active trip can just be the most recent trip in the collection?

**Comment by felixrieseberg** [comment]
I would like to keep this open, as the data pipeline won't be able to tell us about the ongoing trip (it only knows about trips once they're finished).

We can work around by doing a simple "hey, did the car move lately", but I'd like to keep this open for tracking.
