### ISSUE TITLE
Marry Vehicle with Device

### ISSUE THREAD

**Issue by felixrieseberg** [felixrieseberg/OxideFleet#69]
We should really deal with only one model and pull vehicle into device, probably via async calls.

**Comment by sedouard** [comment]
+100

On Monday, May 11, 2015, Felix Rieseberg <notifications@github.com> wrote:

> We should really deal with only one model and pull vehicle into device,
> probably via async calls.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/felixrieseberg/OxideFleet/issues/69>.
>


-- 
Steven Edouard
Computer Engineering, Undergraduate
Email: sedouard@ufl.edu
Mobile: 4079638488
