### ISSUE TITLE
Implement Messaging for Driving Sessions

### ISSUE THREAD

**Issue by felixrieseberg** [felixrieseberg/OxideFleet#9]
Here's the spec that's coming down from Nitrogen - we just need to subscribe and capture it.

```
id: xxxxxx
type: '_driveSummary' (custom message
    for now)
body: {
    start: {
        ts: xx
        latitude: xx,
        longitude: xx,
        altitude ?
    },
    finish: {
        ts: xx,
        latitude: xx,
        longitude: xx
    }
    distance: xx,
    duration: xx,
    driver: xx
}
```
Then, to pull out the location messages corresponding to a drive session, just do a range query with the SDK:

```
nitrogen.Message.find(session, {
    from: < device id > ,
    type: 'location',
    ts: {
        $gte: driveSummary.start.ts
    },
    ts: {
        $lte: driveSummary.stop.ts
    }
}, {}, function(err, messages) {
    // ...
});
```

**Comment by deadlyfingers** [comment]
Are we using fixtures.js for dummy data for this or what endpoint do we use here? Also is this to be displayed on Dashboard, or a separate page?

**Comment by felixrieseberg** [comment]
Since the data is coming down via Nitrogen, we can't use fixtures - but that's fine, we can implement this until data is coming down. I can take care of it.
